version: '3'

services:
  eve-calender:
    ports:
      - "80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - USER_AGENT=your-user-agent-here
      - CLIENT_ID=your-client-id
      - CLIENT_SECRET=your-client-secret
      - BASE_URL=your-base-url
      - MONGO_DB=admin
      - MONGO_USERNAME=username
      - MONGO_PASSWORD=SelectAnActuallyG00dPasswordH3rePl0x
      - MONGO_PORT=27017
      - MONGO_HOST=mongo
    ports:
      - "80"
  mongo:   
    environment:      
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: SelectAnActuallyG00dPasswordH3rePl0x
  mongo-express:    
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: username
      ME_CONFIG_MONGODB_ADMINPASSWORD: SelectAnActuallyG00dPasswordH3rePl0x